---
- hosts: localhost
  gather_facts: false
  vars:
    sample_password: my_password

  tasks:
    - name: password_hash sample
      ansible.builtin.debug:
        msg: "{{ sample_password | ansible.builtin.password_hash }}"
