---
- hosts: docker
  gather_facts: false

  tasks:
    - name: wait for container "healthy"
      community.docker.docker_container_info:
        name: http_app
      register: httpapp_info_result
      until: httpapp_info_result.container.State.Health.Status == "healthy"
      retries: 10
      delay: 5
