---
all:
  vars:
    ansible_user: watari
    ansible_password: pass
  hosts:
    master:
      ansible_host: 192.168.0.100
  children:
    workers:
      hosts:
        worker1:
          ansible_host: 192.168.0.101
        worker2:
          ansible_host: 192.168.0.102
        worker3:
          ansible_host: 192.168.0.103
